# Generated by Django 5.0.4 on 2024-04-28 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_student'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student',
        ),
    ]
