# Generated by Django 5.0.4 on 2024-05-04 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_student'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'managed': False},
        ),
    ]
