# Generated by Django 5.0.4 on 2024-05-04 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_issuebook'),
    ]

    operations = [
        migrations.CreateModel(
            name='sStudent',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('email', models.EmailField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'student',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
