# Generated by Django 5.0.4 on 2024-05-04 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_sstudent_delete_student'),
    ]

    operations = [
        migrations.DeleteModel(
            name='sStudent',
        ),
    ]
