# Generated by Django 5.0.4 on 2024-05-05 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_delete_sstudent'),
    ]

    operations = [
        migrations.CreateModel(
            name='sStudent',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('email', models.EmailField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'student',
                'managed': False,
            },
        ),
        migrations.RemoveField(
            model_name='borrower',
            name='books_borrowed',
        ),
        migrations.RemoveField(
            model_name='borrower',
            name='user',
        ),
        migrations.DeleteModel(
            name='BorrowedBook',
        ),
        migrations.DeleteModel(
            name='Borrower',
        ),
    ]
